name = "savy"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "savy_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "savy.wasm"
command = "npm run build:release"
